GET http://127.0.0.1:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZla3NpIiwiaWQiOiI2MThiOWJjOTAxYTNkYWVhN2E2NGI3MWEiLCJpYXQiOjE2Mzc0NDIwNDF9.V3HhAmfo--61SqjE5K2jhGYX9nJMjl0H42EkinE-BWo
